### ISSUE TITLE
add CR column

### ISSUE THREAD

**Issue by karnelcore** [si13n/projectfire#10]
need CR column with auto filling from database if it present

**Comment by tooolya** [comment]
Need to re-think logic of auto task creation. Now is new.issue or new.tms -> new.task. 
To have correct CR - new.issue.cr or new.tms -> new.task. To be done.

**Comment by tooolya** [comment]
Some thoughts for new logic:

- Create link between CRs and issues. All CRs per issue are shown as additional information. 
- After task is set closed - check if all CRs are in Tested or Closed status,
- If not - create new task with the same issue, create new actions for CRs left (copy estimated time from previous task?), add link to previous task,set target release as Not In Scope
- Need to create new page which will show actions per target release and grouped by task_name/id

@si13n please review.

**Comment by tooolya** [comment]
Fixed by @si13n
