### ISSUE TITLE
Task without issue

### ISSUE THREAD

**Issue by okunava** [si13n/projectfire#7]
Task - 1483 without issue assigned. 

**_Removed screenshot in the name of all possible rules, which can make us sad._**

**Comment by tooolya** [comment]
Confirm as a defect. Need to parse correctly issues that was found on another project, but processed in current.

**Comment by tooolya** [comment]
Temporary fixed. Need to re-think update process

**Comment by tooolya** [comment]
Will be implemented under issue #10
